### ISSUE TITLE
[Scaladoc] Customize classifier

### ISSUE THREAD

**Issue by dszakallas** [aalmiray/kordamp-gradle-plugins#130]
Hi! 
I would like to generate Scaladoc JARs with the following name `my-project-1.0.0-javadoc.jar`
I think this can be done by customizing the classifier given to the scaladocJar task. Do you accept a PR for this?

**Comment by aalmiray** [comment]
Good idea. For consistency, this feature should be implemented similarly as the `groovydoc.replaceJavadoc` config setting (https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_groovydoc_dsl)
