### ISSUE TITLE
[Licensing] Add mappings and a task for Gradle build files

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#137]
I suggest adding license checks for all Gradle build files.

I'm not sure if everyone wants their build files to have license headers, so perhaps there could be an opt-out (or even an opt-in) in the `licensing` extension.

----

https://github.com/aalmiray/kordamp-gradle-plugins/blob/d4042e43ead038184dd493fb165d7ae09120290e/plugins/licensing-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/licensing/LicensingPlugin.groovy#L212-L215

I suggest adding (I'm not sure if the syntax is correct):
```groovy
     gradle = 'SLASHSTAR_STYLE'
     gradle.kts = 'SLASHSTAR_STYLE'
```

Additionaly, I suggest registering a task like this one: https://github.com/tlinkowski/tlinkowski-superpom/blob/c5b8de90aee21a50306bb559ae95f85a57bfcb53/build.gradle.kts#L122-L130

**Comment by tlinkowski** [comment]
Thanks!

One more thing - the mappings that I proposed aren't in the commit:

```groovy
     gradle = 'SLASHSTAR_STYLE'
     gradle.kts = 'SLASHSTAR_STYLE'
```

Is it an overlooking, or are they redundant?

**Comment by aalmiray** [comment]
The mappings are applied explicitly to the `licenseGradle` and `licenseFormatGradle` tasks.

**Comment by tlinkowski** [comment]
Hm, I'm afraid I don't understand. The only place where I see the mappings applied is here:

https://github.com/aalmiray/kordamp-gradle-plugins/blob/3d7315ef376f82d1e1aa2b3893103de69f93a3cb/plugins/licensing-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/licensing/LicensingPlugin.groovy#L212-L217

Anyway, if I remove the mappings for `gradle` and `kts` files in my project, I get the following warnings:
```
Unknown file extension: build.gradle.kts
Unknown file extension: settings.gradle.kts
```

which stem from Hierynomus' License plugin:

https://github.com/hierynomus/license-gradle-plugin/blob/dca3e572ee071554dc3a65d2f41936244ea6d2f8/src/main/groovy/nl/javadude/gradle/plugins/license/maven/AbstractLicenseMojo.java#L139

AFAIU, it doesn't know that `.gradle` = `.groovy`, and `.kts` = `.kt`.
