### ISSUE TITLE
[Plugin] `{pluginName}PluginMarkerMaven` publication is not properly configured

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#167]
This continues our discussion from https://github.com/aalmiray/kordamp-gradle-plugins/issues/96#issuecomment-519831951.

As far as I understand the code, `{pluginName}PluginMarkerMaven` is *not* configured by your plugins, i.e. `PublishingUtils.configurePom` is not called for it (it's called only for `pluginMaven`):
https://github.com/aalmiray/kordamp-gradle-plugins/blob/6ba1d112f2562ca140b8ef841b7448dc0c3debf4/plugins/plugin-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/plugin/PluginPlugin.groovy#L129-L142

I worked around this by [calling it on my own](https://github.com/tlinkowski/tlinkowski-superpom/blob/66a04b522099885a41381da94a71b8f9893ef828/buildSrc/src/main/kotlin/pl/tlinkowski/gradle/my/buildsrc/plugin/IncompletePluginMarkerPublicationWorkaroundPlugin.kt#L44-L53) 🙂

**Comment by tlinkowski** [comment]
This is more complicated than I initially thought. After all, I had to remove `PluginPlugin` altogether because it caused my `javadoc` artifact to break (see https://github.com/tlinkowski/tlinkowski-superpom/issues/52).

**Comment by aalmiray** [comment]
I believe this is now covered in the latest version of the `publishing` plugin.
