### ISSUE TITLE
[ScalaDoc] How can i use this to generate scala doc and aggregate

### ISSUE THREAD

**Issue by ruanwenjun** [aalmiray/kordamp-gradle-plugins#170]
Like scaladoc in sbt

**Comment by aalmiray** [comment]
Please refer to the "Scaladoc" section of the Guide -> https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_scaladoc

**Comment by ruanwenjun** [comment]
Thank you.
