### ISSUE TITLE
Support for static analysis tools

### ISSUE THREAD

**Issue by musketyr** [aalmiray/kordamp-gradle-plugins#210]
the location of the configuration files for codenarc and checkstyle should follow the default conventions (

```
<root>
└── config
    └── checkstyle
        └── checkstyle.xml
        └── suppressions.xml
```

and

```
<root>
└── config
    └── codenarc
        └── codenarc.xml
```

- [ ] init task to generate recommended checkstyle configuration
- [ ] init task to generate recommended codenarc configuration
- [ ] automatically apply checkstyle task for java and groovy projects if the configuration is present
- [ ] automatically apply codenarc task for groovy projects if the configuration is present
- [ ] add an aggregate task for checkstyle (or maybe just declare one checkstyle task for all/each sourcesets in the project instead of adding checkstyle to each subproject), the individual tasks should not fail if aggregate tasks is running
- [ ] add an aggregate task for codenarc (or maybe just declare one codenarc task for all/each sourcesets in the project instead of adding codenarc to each subproject), the individual tasks should not fail if aggregate tasks is running
- [ ] the preferred output location of the tasks should be `report/codenarc|checkstyle/<subproject name>`
- [ ] the default output format should be just `html`
- [ ] the minimal configuration inside `config.checkstyle|codenarc` should contain `toolVersion`, `maxWarnings`, `maxErrors` resp. `maxPriority[1|2|3]Violations`

**Comment by aalmiray** [comment]
Similar support for Pmd would be great too

**Comment by ursjoss** [comment]
Support for detekt would also be great.
