### ISSUE TITLE
support for BinTray publish flag

### ISSUE THREAD

**Issue by musketyr** [aalmiray/kordamp-gradle-plugins#214]
it would nice to have `publish` flag as a part `config.bintray` so I don't have to specify it in the `subprojects` block.

**Comment by musketyr** [comment]
here's the[ link to the BinTray DSL](https://github.com/bintray/gradle-bintray-plugin/blob/master/README.md#plugin-dsl)

```
config {
    bintray {                                                             
        credentials {
            username = project.bintrayUsername
            password = project.bintrayApiKey
        }
        publish    = true
        userOrg    = 'joecool'
        name       = rootProject.name
        githubRepo = 'joecool/sample'
    }
}
```

will apply `bintray.publish = true` to all subprojects.

an alternative to this is to set `bintray.publish = true` when `config.release == true`

**Comment by aalmiray** [comment]
`config.bintray.publish` is set to `false` by default, too risky to let if be `true`. I think this should be a conscious decision made by developers themselves and not by plugin authors.

**Comment by musketyr** [comment]
Sounds fair.
