### ISSUE TITLE
Provide Gradle Kotlin DSL examples in documentation

### ISSUE THREAD

**Issue by aalmiray** [aalmiray/kordamp-gradle-plugins#25]
As explained at https://github.com/gradle/gradle/issues/6790; follow tabbed alternative shown by @bmuschko at https://github.com/bmuschko/gradle-docker-plugin/pull/677

**Comment by eriwen** [comment]
This is great news. I wonder if you had seen [this post](https://blog.gradle.org/groovy-kotlin-dsl-samples) before for choosing DSLs via tabs?

The advantages of the approach in the post are
 * User DSL preferences are remembered client-side
 * Neato little Groovy and Kotlin logos for your tabs and file names
 * No need to include zepto/jquery/etc just for this

Related, I have had a TODO to open source the asciidoctor extensions that Gradle uses here that make samples authoring in Asciidoctor particularly nice. Is that something you'd be interested in?

**Comment by jlstrater** [comment]
Sure! Let's chat when you have some time.

**Comment by bmuschko** [comment]
I am sure the community would appreciate an AsciiDoctorJ extension for their multi-lingual plugins. 👍 The entry barrier for writing such docs should be as low as possible.

**Comment by aalmiray** [comment]
Indeed. But in order to appeal to a much wider audience such extension should be written in Ruby and its language recognition should be pluggable, not just Groovy and Kotlin as it currently stands 😄
