### ISSUE TITLE
[Base] Required (?) "license" block isn't properly documented

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#82]
Steps to reproduce:
1. Create an empty Gradle project with proper structure (docs / subprojects).
2. Apply the [Base](https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_base) plugin.
3. Configure the "release" and "info" properties (like [here](https://github.com/aalmiray/kordamp-gradle-plugins/blob/master/subprojects/guide/src/docs/asciidoc/project-structure.adoc)).
4. Try to build the project.

You should get the following warning: "[Project name] No licenses have been defined" ([source](https://github.com/aalmiray/kordamp-gradle-plugins/blob/11713ba06738a936856892763ceeb94e0cf4e15a/plugins/base-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/base/model/LicenseSet.groovy#L95)).

When you add the "licenses" property, everything works fine.

---

I file this issue because:
- section [5.2.1. Base: DSL](https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_base_dsl) doesn't mention the "license" property at all
- section [5.2.2. Base: Tasks](https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_base_tasks) does mention the property, but only in terms of disabling the feature

So either I mistunderstood something or there's some inconsistency which just kindly want to point out 🙂

---

PS. Thanks for your wonderful set of plugins, Andres! :+1:

**Comment by aalmiray** [comment]
The reason why sections `5.2.1` and `5.2.2` do not mention the `license` block is because these sections refer to `config.info` whereas `license` is a sibling block, located at `config.license` as shown at section [4. Project DSL](https://aalmiray.github.io/kordamp-gradle-plugins/#_project_dsl).

However it should be possible to configure a project without forcing the use of a `license` block (it's recommended to do so btw). The guide should make explicit that one can write the following

    config {
        license { enabled = false }
    }

**Comment by tlinkowski** [comment]
Yeah, I'll include the license 🙂 I'm just trying to do this incrementally: applying Base requires significant additions to `build.gradle`, so I wanted `info` and `license` introduced in separate commits.

And section 5.2.2 actually *does* mention `license {enabled = false}`, but since `license` wasn't mentioned in 5.2.1, I was surprised.

In other words, it seems to me (but I might've misunderstood sth) that Base actually *applies* License, but it's not documented with the appropriate **applies** header (like [here](https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_apidoc)).

**Comment by aalmiray** [comment]
As it happens, `base` does not apply `license` but it does validate it by default. I removed this constraint with the commit linked above.

**Comment by tlinkowski** [comment]
That solves it, thanks a lot!
