### ISSUE TITLE
[Test] Rename to Testing

### ISSUE THREAD

**Issue by aalmiray** [aalmiray/kordamp-gradle-plugins#84]
Use of `test` as top level block is confusing

 - [ ] rename base `Test` to `Testing`.
 - [ ] deprecate `test` in `config`. Usage of this method should output a warning.
 - [ ] add `testing` accessor to `config`.
 - [ ] rename plugin `Test` to `Testing`.
 - [ ] add new plugin id `org.kordamp.gradle.testing`.
 - [ ] keep `org.kordamp.gradle.test` for compatibility.
 - [ ] update guide with new names.

**Comment by tlinkowski** [comment]
The part "collides with inner node and hyeronimous' plugin" doesn't seem to apply in this case, is that right?

**Comment by aalmiray** [comment]
Indeed. The joys of copy&pasting when you’re falling asleep

**Comment by aalmiray** [comment]
As it happens base does not apply license but validates it eagerly, and that’s the problem, it should validate license just like publishing (conditionally).

Thank you very much for your feedback!

**Comment by tlinkowski** [comment]
Thank you, and you're welcome!

PS. You might want to move the last two comment to #82 :wink:
