### ISSUE TITLE
[Jacoco] Allow skipping modules that have no tests

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#85]
In my little project, I have a test module ([unij-test](https://github.com/tlinkowski/UniJ/tree/master/subprojects/unij-test)) with no tests whatsoever (the module just provides shared test code for other modules).

When I run standard `jacocoTestReport` for `unij-test`, it gets `SKIPPED`.

However, when I apply `org.kordamp.gradle.jacoco`, and then run its `jacocoRootReport`, I get the following error:

> Unable to read [path]\UniJ\subprojects\unij-test\build\jacoco\test.exec

I'm not sure if this is intentional or not, but I think that it could be useful to have some way (either implicit or explicit) of skipping a module in JaCoCo merging/reporting.

PS. Note that, after all, I haven't used this plugin, because I realized that a special [codecov uploader](https://github.com/codecov/codecov-python) can also do the report assembling for me.

**Comment by aalmiray** [comment]
Here's one way to conditionally skip running JaCoCo on a project that does not define tests under `src/test'

    jacoco {
        enabled = subproject.file('src/test').exists()
    }

Take note that JaCoCo will be applied to all test tasks, including those defined by `integration-test` and `functional-test` plugins.

**Comment by tlinkowski** [comment]
Yes, good point - if my library were more complex and I needed integration/functional tests, then this plugin would come in very handy
