### ISSUE TITLE
[Settings] Plugin doesn't seem to work in Kotlin DSL

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#90]
Applying the [Settings plugin](https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_settings) to the following [`settings.gradle.kts`](https://github.com/tlinkowski/basic-annotations/blob/settings-kotlin-dsl/settings.gradle.kts#L18) (Kotlin DSL) results in the following build error:

```
* Where:
Settings file '/home/travis/build/tlinkowski/basic-annotations/settings.gradle.kts' line: 30
* What went wrong:
Script compilation errors:
  Line 30: projects {
           ^ Unresolved reference: projects
  Line 31:   directories = listOf("subprojects")
             ^ Unresolved reference: directories
```

Full details in [Travis build log](https://travis-ci.com/tlinkowski/basic-annotations/builds/104122841#L471).

**Comment by aalmiray** [comment]
This is a known limitation in Kotlin DSL. The alternative is to write

    configure<org.kordamp.gradle.plugin.settings.ProjectsExtension> {
        directories = listOf("subprojects")
    }

Will update the guide with this information.

**Comment by tlinkowski** [comment]
Thanks!

But that's indeed a serious limitation of Kotlin DSL 🙁
