### ISSUE TITLE
[Plugin] Configure java-gradle-plugin and publish-plugin plugins

### ISSUE THREAD

**Issue by aalmiray** [aalmiray/kordamp-gradle-plugins#94]

**Comment by tlinkowski** [comment]
Cool! I'm about to try creating my [Gradle SuperPOM](http://andresalmiray.com/the-gradle-superpom/), and I see "plugin plugin" should make it much easier 🙂

**Comment by aalmiray** [comment]
Watch out using the `plugin-gradle-plugin` for the Gradle Super POM idea, as this plugin will publish artifacts to the Gradle Plugin Portal. You'r own Super POM should not be published to the portal IMHO.

There's still one more thing that needs to be done before a Super POM can be consumed from Bintray/JCenter: the `org.kordamp.gradle.bintray` does not publish the plugin marker publication created by the `java-gradle-plugin` plugin.

**Comment by tlinkowski** [comment]
> Watch out using the `plugin-gradle-plugin` for the Gradle Super POM idea, as this plugin will publish artifacts to the Gradle Plugin Portal. You'r own Super POM should not be published to the portal IMHO.

You're right! Here's a quote from the [user guide](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:publishing_your_plugin):

> If you are publishing your plugin internally for use within your organization, you can publish it like any other code artifact. See the Ivy and Maven chapters on publishing artifacts.
> 
> If you are interested in publishing your plugin **to be used by the wider Gradle community**, you can publish it to the Gradle Plugin Portal.

----

> There's still one more thing that needs to be done before a Super POM can be consumed from Bintray/JCenter: the `org.kordamp.gradle.bintray` does not publish the plugin marker publication created by the `java-gradle-plugin` plugin.

Thanks for the tip, I just learned about those [plugin marker artifacts](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers). So I guess I'd have to configure publishing of this on my own.
