### ISSUE TITLE
Feature request: support for creating Gradle SuperPOM

### ISSUE THREAD

**Issue by tlinkowski** [aalmiray/kordamp-gradle-plugins#96]
I wonder: would it be possible to have some support from Kordamp for creating a [Gradle SuperPOM](http://andresalmiray.com/the-gradle-superpom/). Do you consider this idea mature enough?

## Minimum support
Minimum support that I imagine would be rather trivial — configuring publishing like the new Plugin plugin, but to Bintray instead of Gradle Plugin Portal (yet including publication of the [plugin marker artifact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers)).

In this case, the DSL would be analogous to the one of the Plugin plugin (`id` + `implementationClass`).

## Maximum support
Pure speculation here (optional read).

I tried to come up with something to:
- avoid creating a custom `SuperpomPlugin` class
- specify the contents of `config` only once
    - you write that "the next iteration of this superpom can consume the last", but doing so would be inconvenient — to change `config` for the Gradle SuperPOM project itself, one would have to make **two** releases

I though of DSL like below for SuperPOM's `build.gradle`, but I now think it's not possible (since the contents of the closures cannot be taken out of context & released in a plugin):

```groovy
config {
  superPom {
    configureAllProjects {
      // here's a Closure with configuration applied to the Gradle SuperPOM (applied immediately) and its target projects (how to export it?), where `this instanceof Project`, e.g.
      config {
        release = (rootProject.findProperty('release') ?: false).toBoolean()
        info {
          vendor = 'Acme'
        }
      }
    }
    configureTargetProjects {
      // here's a Closure with configuration applied only to target projects (how to export it?), where `this instanceof Project`, e.g.
      apply plugin: 'org.kordamp.gradle.project'
      config {
        info {
        }
      }
      allprojects {
        repositories {
          mavenCentral()
          mavenLocal()
        }
      }
    }
  }
}
```

But perhaps there are some other ways of making the creation of SuperPOM easier, e.g.:
- avoid custom `SuperpomPlugin` class
    - this is perhaps rather hard to avoid
- specify the contents of `config` only once
    - maybe configuring the build so that it first publishes a minimum-configured plugin to local Maven, and then kind-of runs the build again (this time applying the local plugin); not sure if at all possible

**Comment by aalmiray** [comment]
I'm afraid the whole point of the Super POM idea is to share configuration with multiple projects, thus you need 2 releases: 1 for the superpom, 1 for each target project. The `org.kordamp.gradle.bintray` plugin ought to pick up the plugin marker publication by default, this is a change coming up in the next release.

**Comment by aalmiray** [comment]
`org.kordamp.gradle.bintray` plugin can now publish the plugin marker publication automatically if the `org.kordamp.gradle.plugin` is applied.

**Comment by tlinkowski** [comment]
Cool, thank you! As far as I understand, this fulfills the "minimum support" request.

As to "maximum support", I'm not sure if we had the same thing in mind, but I think I'd better let it go for now. When I have my Gradle SuperPOM ready, and if I gain any useful insights about this, I might revisit.

**Comment by tlinkowski** [comment]
> `org.kordamp.gradle.bintray` plugin can now publish the plugin marker publication automatically if the `org.kordamp.gradle.plugin` is applied.

Your Bintray plugin indeed picks up the plugin marker publications, and my release works fine on [JCenter](https://bintray.com/bintray/jcenter?filterByPkgName=tlinkowski-superpom).

However, I can't sync it to Maven Central because the publications don't have required metadata: https://github.com/tlinkowski/tlinkowski-superpom/issues/50

Guess will have to set up copying this from the `main` publication, if I want to use the plugin from Maven Central.

**Comment by aalmiray** [comment]
I think this is a problem with lazy evaluation. Both the `java-gradle-plugin` and kordamp's `publishing` plugins configure a matching publication but the former is taken instead of the latter. I'll have to figure out a way to work around it.

**Comment by tlinkowski** [comment]
OK, thanks for the feedback!

I'll play with the order of plugin application myself, then. As far as I recall, both plugins add their `afterEvaluate` handlers, so it seems there's not much you could do (other than hacks like `taskGraph.whenReady`).
